version: '3.4'

services:
  server:
    build: 
      context: ./Server
      dockerfile: Dockerfile
    container_name: Server
    ports:
      - "5210:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: Client
    ports:
      - "3000:80"
    networks:
      - mynetwork

  db:
    image: postgres
    container_name: Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yazan55
      POSTGRES_DB: Uia-tools
    ports:
      - "5434:5432"
    volumes:
      - my-db:/var/lib/postgresql/data
      - ./tool03.sql:/docker-entrypoint-initdb.d/tool03.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  my-db:
