version: '3.4'

services:
  server:
    build: 
      context: ./Server  # Path to your ASP.NET Core project folder
      dockerfile: Dockerfile
    container_name: Server
    ports:
      - "8000:80"

  client:
    build: 
      context: ./client  # Path to your React project folder
      dockerfile: Dockerfile
    container_name: Client
    ports:
      - "3000:80"
